branch-defaults:
  main:
    environment: entrega-1
    group_suffix: null
global:
  application_name: miso-devops-santiago
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.12
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  use_launch_template: true
  workspace_type: Application
